// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmCaD8fPkgwpAw5qN0aUP-SyhTk-RztnQ',
    appId: '1:827960456179:web:b2366c9b850fb8dee79886',
    messagingSenderId: '827960456179',
    projectId: 'health-app-83149',
    authDomain: 'health-app-83149.firebaseapp.com',
    storageBucket: 'health-app-83149.firebasestorage.app',
    measurementId: 'G-XV1SY0K4FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDTGr2qBHCjKgkdUnDeACg7r-2RJJSGs8',
    appId: '1:827960456179:android:d5ebcaa0c64cd023e79886',
    messagingSenderId: '827960456179',
    projectId: 'health-app-83149',
    storageBucket: 'health-app-83149.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkvi3mBYv6t-c4R3uxlI0rurhw44qYBOY',
    appId: '1:827960456179:ios:bfd53b4771c81799e79886',
    messagingSenderId: '827960456179',
    projectId: 'health-app-83149',
    storageBucket: 'health-app-83149.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkvi3mBYv6t-c4R3uxlI0rurhw44qYBOY',
    appId: '1:827960456179:ios:bfd53b4771c81799e79886',
    messagingSenderId: '827960456179',
    projectId: 'health-app-83149',
    storageBucket: 'health-app-83149.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmCaD8fPkgwpAw5qN0aUP-SyhTk-RztnQ',
    appId: '1:827960456179:web:d86f0261eda900a3e79886',
    messagingSenderId: '827960456179',
    projectId: 'health-app-83149',
    authDomain: 'health-app-83149.firebaseapp.com',
    storageBucket: 'health-app-83149.firebasestorage.app',
    measurementId: 'G-MC73FF604Z',
  );

}